[versions]
agp = "8.7.3"
android-compileSdk = "35"
android-minSdk = "24"
android-targetSdk = "35"
androidx-activityCompose = "1.10.1"
compose-plugin = "1.7.3"
compottie = "2.0.0-rc04"
junit = "4.13.2"
kotlin = "2.1.20-RC"
kotlinx-datetime = "0.6.2"
koin = "4.0.2"
ktor = "3.1.1"
coroutines = "1.10.1"
lifecycleViewmodel = "2.8.7"
buildkonfig = "0.15.2"
navigationCompose = "2.8.0-alpha10"
uriKmp = "0.0.18"
spotless = "6.21.0"
composeHotReload = "1.0.0-alpha01"

[libraries]
androidx-lifecycle-viewmodel = { module = "androidx.lifecycle:lifecycle-viewmodel", version.ref = "lifecycleViewmodel" }
kotlin-test = { module = "org.jetbrains.kotlin:kotlin-test", version.ref = "kotlin" }
kotlin-test-junit = { module = "org.jetbrains.kotlin:kotlin-test-junit", version.ref = "kotlin" }
junit = { group = "junit", name = "junit", version.ref = "junit" }
androidx-activity-compose = { module = "androidx.activity:activity-compose", version.ref = "androidx-activityCompose" }

kotlinx-datetime = { module = "org.jetbrains.kotlinx:kotlinx-datetime", version.ref = "kotlinx-datetime" }
kotlinx-coroutines = {module = "org.jetbrains.kotlinx:kotlinx-coroutines-core", version.ref="coroutines"}
kotlinx-coroutines-swing = {module = "org.jetbrains.kotlinx:kotlinx-coroutines-swing", version.ref="coroutines"}

ktor-client-okhttp = {module = "io.ktor:ktor-client-android", version.ref = "ktor"}
ktor-client-core = {module = "io.ktor:ktor-client-core", version.ref = "ktor"}
ktor-client-content-negotiation = {module = "io.ktor:ktor-client-content-negotiation", version.ref = "ktor"}
ktor-client-java = {module = "io.ktor:ktor-client-java", version.ref = "ktor"}
ktor-client-serialization = {module = "io.ktor:ktor-serialization-kotlinx-json", version.ref = "ktor"}
ktor-client-logging = {module = "io.ktor:ktor-client-logging", version.ref = "ktor"}
ktor-client-darwin = { module = "io.ktor:ktor-client-darwin", version.ref = "ktor" }

koin-compose = {group = "io.insert-koin", name = "koin-compose", version.ref="koin"}
koin-compose-vm = {group = "io.insert-koin", name = "koin-compose-viewmodel", version.ref="koin"}

compottie = { module = "io.github.alexzhirkevich:compottie", version.ref = "compottie" }

navigation-compose = { module = "org.jetbrains.androidx.navigation:navigation-compose", version.ref = "navigationCompose" }

uri-kmp = { module = "com.eygraber:uri-kmp", version.ref = "uriKmp" }

[plugins]
androidApplication = { id = "com.android.application", version.ref = "agp" }
androidLibrary = { id = "com.android.library", version.ref = "agp" }
jetbrainsCompose = { id = "org.jetbrains.compose", version.ref = "compose-plugin" }
compose-compiler = { id = "org.jetbrains.kotlin.plugin.compose", version.ref = "kotlin" }
kotlinMultiplatform = { id = "org.jetbrains.kotlin.multiplatform", version.ref = "kotlin" }
kotlinSerialization = { id = "org.jetbrains.kotlin.plugin.serialization", version.ref = "kotlin" }
buildkonfig = { id = "com.codingfeline.buildkonfig", version.ref = "buildkonfig" }
spotless = { id = "com.diffplug.spotless", version.ref = "spotless" }

composeHotReload = { id = "org.jetbrains.compose.hot-reload", version.ref = "composeHotReload" }
